version: "3.7"
services:
  rss-api-backend:
    container_name: rss-api-backend
    image: treaudde/simple-development-environment:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

#  rss-database:
#    container_name: rss-database
#    image: mysql:5
#    ports:
#      - "33066:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root_password
#      MYSQL_DATABASE: rss
#      MYSQL_USER: rss
#      MYSQL_PASSWORD: insecure_password



